# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steward/maintenance.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from steward import asset_pb2 as steward_dot_asset__pb2
from steward import schedule_pb2 as steward_dot_schedule__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steward/maintenance.proto',
  package='steward',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19steward/maintenance.proto\x12\x07steward\x1a\x13steward/asset.proto\x1a\x16steward/schedule.proto\"\x92\x01\n\x0bMaintenance\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1d\n\x05\x61sset\x18\x04 \x01(\x0b\x32\x0e.steward.Asset\x12\x0f\n\x07\x65nabled\x18\x05 \x01(\x08\x12#\n\x08schedule\x18\x06 \x01(\x0b\x32\x11.steward.Schedule\"$\n\x15GetMaintenanceRequest\x12\x0b\n\x03_id\x18\x01 \x01(\t\"\'\n\x18\x44\x65leteMaintenanceRequest\x12\x0b\n\x03_id\x18\x01 \x01(\t\"R\n\x18UpdateMaintenanceRequest\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12)\n\x0bmaintenance\x18\x02 \x01(\x0b\x32\x14.steward.Maintenance\"8\n\x17ListMaintenancesRequest\x12\x1d\n\x05\x61sset\x18\x02 \x01(\x0b\x32\x0e.steward.Assetb\x06proto3'
  ,
  dependencies=[steward_dot_asset__pb2.DESCRIPTOR,steward_dot_schedule__pb2.DESCRIPTOR,])




_MAINTENANCE = _descriptor.Descriptor(
  name='Maintenance',
  full_name='steward.Maintenance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='steward.Maintenance._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='steward.Maintenance.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='steward.Maintenance.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asset', full_name='steward.Maintenance.asset', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='steward.Maintenance.enabled', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schedule', full_name='steward.Maintenance.schedule', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=230,
)


_GETMAINTENANCEREQUEST = _descriptor.Descriptor(
  name='GetMaintenanceRequest',
  full_name='steward.GetMaintenanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='steward.GetMaintenanceRequest._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=268,
)


_DELETEMAINTENANCEREQUEST = _descriptor.Descriptor(
  name='DeleteMaintenanceRequest',
  full_name='steward.DeleteMaintenanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='steward.DeleteMaintenanceRequest._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=309,
)


_UPDATEMAINTENANCEREQUEST = _descriptor.Descriptor(
  name='UpdateMaintenanceRequest',
  full_name='steward.UpdateMaintenanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='steward.UpdateMaintenanceRequest._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maintenance', full_name='steward.UpdateMaintenanceRequest.maintenance', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=393,
)


_LISTMAINTENANCESREQUEST = _descriptor.Descriptor(
  name='ListMaintenancesRequest',
  full_name='steward.ListMaintenancesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset', full_name='steward.ListMaintenancesRequest.asset', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=451,
)

_MAINTENANCE.fields_by_name['asset'].message_type = steward_dot_asset__pb2._ASSET
_MAINTENANCE.fields_by_name['schedule'].message_type = steward_dot_schedule__pb2._SCHEDULE
_UPDATEMAINTENANCEREQUEST.fields_by_name['maintenance'].message_type = _MAINTENANCE
_LISTMAINTENANCESREQUEST.fields_by_name['asset'].message_type = steward_dot_asset__pb2._ASSET
DESCRIPTOR.message_types_by_name['Maintenance'] = _MAINTENANCE
DESCRIPTOR.message_types_by_name['GetMaintenanceRequest'] = _GETMAINTENANCEREQUEST
DESCRIPTOR.message_types_by_name['DeleteMaintenanceRequest'] = _DELETEMAINTENANCEREQUEST
DESCRIPTOR.message_types_by_name['UpdateMaintenanceRequest'] = _UPDATEMAINTENANCEREQUEST
DESCRIPTOR.message_types_by_name['ListMaintenancesRequest'] = _LISTMAINTENANCESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Maintenance = _reflection.GeneratedProtocolMessageType('Maintenance', (_message.Message,), {
  'DESCRIPTOR' : _MAINTENANCE,
  '__module__' : 'steward.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:steward.Maintenance)
  })
_sym_db.RegisterMessage(Maintenance)

GetMaintenanceRequest = _reflection.GeneratedProtocolMessageType('GetMaintenanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMAINTENANCEREQUEST,
  '__module__' : 'steward.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:steward.GetMaintenanceRequest)
  })
_sym_db.RegisterMessage(GetMaintenanceRequest)

DeleteMaintenanceRequest = _reflection.GeneratedProtocolMessageType('DeleteMaintenanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEMAINTENANCEREQUEST,
  '__module__' : 'steward.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:steward.DeleteMaintenanceRequest)
  })
_sym_db.RegisterMessage(DeleteMaintenanceRequest)

UpdateMaintenanceRequest = _reflection.GeneratedProtocolMessageType('UpdateMaintenanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMAINTENANCEREQUEST,
  '__module__' : 'steward.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:steward.UpdateMaintenanceRequest)
  })
_sym_db.RegisterMessage(UpdateMaintenanceRequest)

ListMaintenancesRequest = _reflection.GeneratedProtocolMessageType('ListMaintenancesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTMAINTENANCESREQUEST,
  '__module__' : 'steward.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:steward.ListMaintenancesRequest)
  })
_sym_db.RegisterMessage(ListMaintenancesRequest)


# @@protoc_insertion_point(module_scope)
