# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steward/maintenance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from steward import schedule_pb2 as steward_dot_schedule__pb2
from steward import snooze_pb2 as steward_dot_snooze__pb2
from steward import asset_pb2 as steward_dot_asset__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steward/maintenance.proto',
  package='steward',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19steward/maintenance.proto\x12\x07steward\x1a\x16steward/schedule.proto\x1a\x14steward/snooze.proto\x1a\x13steward/asset.proto\"\xa1\x01\n\x0bMaintenance\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12#\n\x08schedule\x18\x04 \x01(\x0b\x32\x11.steward.Schedule\x12\x1f\n\x06snooze\x18\x05 \x01(\x0b\x32\x0f.steward.Snooze\x12\x1d\n\x05\x61sset\x18\x06 \x01(\x0b\x32\x0e.steward.Assetb\x06proto3')
  ,
  dependencies=[steward_dot_schedule__pb2.DESCRIPTOR,steward_dot_snooze__pb2.DESCRIPTOR,steward_dot_asset__pb2.DESCRIPTOR,])




_MAINTENANCE = _descriptor.Descriptor(
  name='Maintenance',
  full_name='steward.Maintenance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='steward.Maintenance.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='steward.Maintenance.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='steward.Maintenance.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schedule', full_name='steward.Maintenance.schedule', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snooze', full_name='steward.Maintenance.snooze', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset', full_name='steward.Maintenance.asset', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=267,
)

_MAINTENANCE.fields_by_name['schedule'].message_type = steward_dot_schedule__pb2._SCHEDULE
_MAINTENANCE.fields_by_name['snooze'].message_type = steward_dot_snooze__pb2._SNOOZE
_MAINTENANCE.fields_by_name['asset'].message_type = steward_dot_asset__pb2._ASSET
DESCRIPTOR.message_types_by_name['Maintenance'] = _MAINTENANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Maintenance = _reflection.GeneratedProtocolMessageType('Maintenance', (_message.Message,), {
  'DESCRIPTOR' : _MAINTENANCE,
  '__module__' : 'steward.maintenance_pb2'
  # @@protoc_insertion_point(class_scope:steward.Maintenance)
  })
_sym_db.RegisterMessage(Maintenance)


# @@protoc_insertion_point(module_scope)
