# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steward/registry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from steward import user_pb2 as steward_dot_user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steward/registry.proto',
  package='steward',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16steward/registry.proto\x12\x07steward\x1a\x12steward/user.proto2\xb8\x01\n\x0bUserService\x12\x33\n\x07GetUser\x12\x17.steward.GetUserRequest\x1a\r.steward.User\"\x00\x12\x39\n\nCreateUser\x12\x1a.steward.CreateUserRequest\x1a\r.steward.User\"\x00\x12\x39\n\tListUsers\x12\x19.steward.ListUsersRequest\x1a\r.steward.User\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[steward_dot_user__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='steward.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=56,
  serialized_end=240,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUser',
    full_name='steward.UserService.GetUser',
    index=0,
    containing_service=None,
    input_type=steward_dot_user__pb2._GETUSERREQUEST,
    output_type=steward_dot_user__pb2._USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='steward.UserService.CreateUser',
    index=1,
    containing_service=None,
    input_type=steward_dot_user__pb2._CREATEUSERREQUEST,
    output_type=steward_dot_user__pb2._USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListUsers',
    full_name='steward.UserService.ListUsers',
    index=2,
    containing_service=None,
    input_type=steward_dot_user__pb2._LISTUSERSREQUEST,
    output_type=steward_dot_user__pb2._USER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
